theme = "eiffel"

[keys.insert]
j = { k = "normal_mode" } # Maps `jk` to exit insert mode

[editor]
cursorline = true
lsp.display-inlay-hints = false
end-of-line-diagnostics = "hint"

[editor.inline-diagnostics]
cursor-line = "disable"

[editor.cursor-shape]
insert = "bar"
select = "underline"

[editor.soft-wrap]
enable = true
